# Generated by Django 3.2.7 on 2021-09-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='Автор')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('linkOfPicture', models.ImageField(blank=True, null=True, upload_to='question_foto', verbose_name='Картинка к вопросу')),
                ('rightAnswer', models.CharField(max_length=50, verbose_name='Ответ')),
                ('wrongAnswerOne', models.CharField(max_length=50, verbose_name='Первый неправильный ответ')),
                ('wrongAnswerTwo', models.CharField(max_length=50, verbose_name='Первый неправильный ответ')),
                ('wrongAnswerThree', models.CharField(max_length=50, verbose_name='Первый неправильный ответ')),
                ('commentForJudge', models.CharField(max_length=400, verbose_name='Комментарий к вопросу')),
                ('aboutQuestion', models.CharField(max_length=1500, verbose_name='Описание вопроса')),
                ('link', models.CharField(max_length=50, verbose_name='Источник информации')),
                ('themeOfQuestion', models.CharField(max_length=50, verbose_name='Тема')),
                ('questionCategory', models.CharField(max_length=50, verbose_name='Категория')),
                ('sectionOfQuestion', models.CharField(max_length=30, verbose_name='Раздел')),
                ('complexityOfQuestion', models.IntegerField(default=0, null=True, verbose_name='Сложность по десятибальной шкале')),
                ('approve', models.IntegerField(default=0, verbose_name='Статус одобрения')),
                ('date_ques_sub', models.DateField(verbose_name='Дата подачи вопроса')),
                ('base_date', models.DateField(null=True, verbose_name='Дата добавления в базу')),
            ],
        ),
    ]
