# Generated by Django 3.2.7 on 2021-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsReviewer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataLoader.questions')),
                ('reviewer', models.CharField(blank=True, max_length=30, verbose_name='Рецензент')),
                ('reviewer_date', models.DateField(blank=True, verbose_name='Дата рецензии')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=400, verbose_name='Комментарий')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataLoader.questions')),
            ],
        ),
    ]
