# Generated by Django 3.2.7 on 2021-09-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0003_alter_questions_rightanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='aboutQuestion',
            field=models.CharField(max_length=1900, verbose_name='Описание вопроса'),
        ),
    ]
