# Generated by Django 3.2.7 on 2021-09-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0004_alter_questions_aboutquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='themeOfQuestion',
            field=models.CharField(max_length=90, verbose_name='Тема'),
        ),
    ]
