# Generated by Django 3.2.7 on 2021-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0005_alter_questions_themeofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='sectionOfQuestion',
            field=models.CharField(max_length=55, verbose_name='Раздел'),
        ),
    ]
