# Generated by Django 3.2.7 on 2021-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0007_alter_questions_themeofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questionCategory',
            field=models.CharField(max_length=90, verbose_name='Категория'),
        ),
    ]
