# Generated by Django 3.2.7 on 2021-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0008_alter_questions_questioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='aboutQuestion',
            field=models.CharField(max_length=2000, verbose_name='Описание вопроса'),
        ),
    ]
