# Generated by Django 3.2.7 on 2021-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0012_alter_questions_themeofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
    ]
