# Generated by Django 3.2.7 on 2021-09-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0013_alter_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeOfQuestion', models.CharField(max_length=150, verbose_name='Тема')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questionCategory',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='themeOfQuestion',
        ),
        migrations.CreateModel(
            name='QuestionsThemesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionCategory', models.CharField(max_length=120, verbose_name='Категория')),
                ('themeOfQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataLoader.questionsthemes')),
            ],
        ),
        migrations.AddField(
            model_name='questionsthemes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataLoader.questions'),
        ),
    ]
