# Generated by Django 3.2.7 on 2021-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoader', '0014_auto_20210917_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsthemes',
            name='question',
        ),
        migrations.AddField(
            model_name='questionsthemes',
            name='question',
            field=models.ManyToManyField(to='dataLoader.Questions'),
        ),
    ]
